
import java.time.LocalTime;
import java.awt.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;





public class CreateActivity extends javax.swing.JFrame {

    /**
     * Creates new form CreateActivity
     */
    public CreateActivity() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonGroup group = new ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        NewActivityLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        TagsLabel = new javax.swing.JLabel();
        CHESS = new javax.swing.JRadioButton();
        SPORTS = new javax.swing.JRadioButton();
        CHAT = new javax.swing.JRadioButton();
        VIDEOGAME = new javax.swing.JRadioButton();
        CINEMA = new javax.swing.JRadioButton();
        QuotaLabel = new javax.swing.JLabel();
        GetName = new javax.swing.JTextField();
        newActivity_Date = new javax.swing.JLabel();
        newActivity_Day = new javax.swing.JLabel();
        newActivity_Month = new javax.swing.JLabel();
        newActivity_Year = new javax.swing.JLabel();
        GetQuota = new javax.swing.JTextField();
        GetMonth = new javax.swing.JTextField();
        GetYear = new javax.swing.JTextField();
        newActivity_Time = new javax.swing.JLabel();
        GetPlace = new javax.swing.JTextField();
        newActivity_Place = new javax.swing.JLabel();
        GetDay = new javax.swing.JTextField();
        GetMinute = new javax.swing.JTextField();
        newActivity_Place1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        GetDescription = new javax.swing.JTextArea();
        CreateActivity_Button = new javax.swing.JButton();
        DANCE = new javax.swing.JRadioButton();
        CreatingActivity = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        GetHour = new javax.swing.JTextField();
        group.add(CHESS);
        group.add(SPORTS);
        group.add(CHAT);
        group.add(VIDEOGAME);
        group.add(CINEMA);
        group.add(DANCE);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 900));

        NewActivityLabel.setBackground(new java.awt.Color(255, 255, 255));
        NewActivityLabel.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        NewActivityLabel.setText("New Activity");

        NameLabel.setBackground(new java.awt.Color(255, 255, 255));
        NameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NameLabel.setText("Name");

        TagsLabel.setBackground(new java.awt.Color(255, 255, 255));
        TagsLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TagsLabel.setText("Tags");

        CHESS.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        CHESS.setText("CHESS");
        CHESS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHESSActionPerformed(evt);
            }
        });

        SPORTS.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        SPORTS.setText("SPORTS");
        SPORTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPORTSActionPerformed(evt);
            }
        });

        CHAT.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        CHAT.setText("CHAT");
        CHAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHATActionPerformed(evt);
            }
        });

        VIDEOGAME.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        VIDEOGAME.setText("VIDEOGAME");
        VIDEOGAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VIDEOGAMEActionPerformed(evt);
            }
        });

        CINEMA.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        CINEMA.setText("CINEMA");

        QuotaLabel.setBackground(new java.awt.Color(255, 255, 255));
        QuotaLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        QuotaLabel.setText("Quota");

        GetName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetNameActionPerformed(evt);
            }
        });

        newActivity_Date.setBackground(new java.awt.Color(255, 255, 255));
        newActivity_Date.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newActivity_Date.setText("Date");

        newActivity_Day.setBackground(new java.awt.Color(255, 255, 255));
        newActivity_Day.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newActivity_Day.setText("Day");

        newActivity_Month.setBackground(new java.awt.Color(255, 255, 255));
        newActivity_Month.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newActivity_Month.setText("Month");

        newActivity_Year.setBackground(new java.awt.Color(255, 255, 255));
        newActivity_Year.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newActivity_Year.setText("Year");

        GetQuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetQuotaActionPerformed(evt);
            }
        });

        GetMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetMonthActionPerformed(evt);
            }
        });

        GetYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetYearActionPerformed(evt);
            }
        });

        newActivity_Time.setBackground(new java.awt.Color(255, 255, 255));
        newActivity_Time.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newActivity_Time.setText("Time");

        GetPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetPlaceActionPerformed(evt);
            }
        });

        newActivity_Place.setBackground(new java.awt.Color(255, 255, 255));
        newActivity_Place.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newActivity_Place.setText("Place");

        GetDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetDayActionPerformed(evt);
            }
        });

        GetMinute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetMinuteActionPerformed(evt);
            }
        });

        newActivity_Place1.setBackground(new java.awt.Color(255, 255, 255));
        newActivity_Place1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newActivity_Place1.setText("Description");

        GetDescription.setColumns(20);
        GetDescription.setRows(5);
        jScrollPane1.setViewportView(GetDescription);

        CreateActivity_Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CreateActivity_Button.setText("Create Activity");
        CreateActivity_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActivity_ButtonActionPerformed(evt);
            }
        });

        DANCE.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        DANCE.setText("DANCE");
        DANCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DANCEActionPerformed(evt);
            }
        });

        CreatingActivity.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CreatingActivity.setText("Create Activity");
        CreatingActivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatingActivityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.setOpaque(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel5.setOpaque(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );

        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText(":");

        GetHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetHourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TagsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QuotaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newActivity_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newActivity_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newActivity_Place, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newActivity_Place1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GetQuota, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GetPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(801, 801, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(newActivity_Day, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GetDay, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(newActivity_Month, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GetMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(newActivity_Year, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addComponent(CreateActivity_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(27, 27, 27)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CreatingActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(GetYear, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(GetName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(GetHour, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(GetMinute, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CHESS, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SPORTS, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(CHAT, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(VIDEOGAME, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CINEMA, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DANCE, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42)
                .addComponent(NewActivityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NewActivityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(NameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(GetName)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CHESS, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(SPORTS, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                    .addComponent(CHAT, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                    .addComponent(VIDEOGAME, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                    .addComponent(CINEMA, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                    .addComponent(DANCE, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(TagsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(QuotaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(GetQuota, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(newActivity_Date, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(newActivity_Day, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(newActivity_Month, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(newActivity_Year, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(GetMonth, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(GetYear, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(GetDay, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(newActivity_Time, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(GetMinute, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                            .addComponent(GetHour, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(newActivity_Place, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(GetPlace, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jScrollPane1)
                                            .addComponent(newActivity_Place1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(CreateActivity_Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(14, 14, 14))
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CreatingActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 23, Short.MAX_VALUE)))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CHATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHATActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CHATActionPerformed

    private void CHESSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHESSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CHESSActionPerformed

    private void SPORTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPORTSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SPORTSActionPerformed

    private void GetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GetNameActionPerformed

    private void GetQuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetQuotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GetQuotaActionPerformed

    private void GetMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GetMonthActionPerformed

    private void GetYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GetYearActionPerformed

    private void GetPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetPlaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GetPlaceActionPerformed

    private void GetDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GetDayActionPerformed

    private void GetTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GetTimeActionPerformed

    private void CreateActivity_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActivity_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateActivity_ButtonActionPerformed

    private void VIDEOGAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VIDEOGAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VIDEOGAMEActionPerformed
    private void DANCEActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void GetHourActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }      
    private void GetMinuteActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }
    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        //this.dispose();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        MainManager.openMainPage(this);
    }          
    private Tag find_tag()
    {
        Tag activityTag = new Tag(Tag.TagType.CHESS);
        ButtonGroup activity_tags = new ButtonGroup();
        activity_tags.add(CHESS);
        activity_tags.add(SPORTS);
        activity_tags.add(CHAT);
        activity_tags.add(VIDEOGAME);
        activity_tags.add(CINEMA);
        activity_tags.add(DANCE);
       
        if(CHESS.isSelected())
        {
            activityTag = new Tag(Tag.TagType.CHESS);
        }
        else if(SPORTS.isSelected())
        {
            activityTag = new Tag(Tag.TagType.SPORTS);
        }
        else if(CHAT.isSelected())
        {
            activityTag = new Tag(Tag.TagType.CHAT);
        }
        else if(VIDEOGAME.isSelected())
        {
            activityTag = new Tag(Tag.TagType.VIDEOGAME);
        }
        else if(CINEMA.isSelected())
        {
            activityTag = new Tag(Tag.TagType.CINEMA);
        }
        else if(DANCE.isSelected())
        {
            activityTag = new Tag(Tag.TagType.DANCE);
        }
        return activityTag;                
    }

    private void CreatingActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatingActivityActionPerformed
        // TODO add your handling code here:
        String name = GetName.getText();
        int Quota = Integer.parseInt(GetQuota.getText());
        Tag activity_tag = find_tag();
        Tag.TagType tagType = activity_tag.getType();
        //TagType tag_of_activity = 
        int Day = Integer.parseInt(GetDay.getText());
        int Month =Integer.parseInt(GetMonth.getText());
        int Year = Integer.parseInt(GetYear.getText());
        String str= ""+ Year+ "-"+ Month + "-" + Day;
        Date date2 = Date.valueOf(str);//converting string into sql date
        //Date date_of_activity = new Date(Year,Month,Day);
        int Hour = Integer.parseInt(GetHour.getText()) ;
        int Minute = Integer.parseInt(GetMinute.getText());
        String Time = Hour + ":" + Minute + ":00"; 
        Time time_of_activity =  java.sql.Time.valueOf(Time);// solve this problem
        String activity_place = GetPlace.getText();
        String activity_definition = GetDescription.getText();
        try {
            Statement stm = MainManager.db.getCon().createStatement();
            //ResultSet resultset2 = stm.executeQuery("SELECT COUNT(actID) FROM acitivities");
            //resultset2.next();
            //int ID2 = resultset.getInt("COUNT(actID)");
            ResultSet resultset = stm.executeQuery("SELECT MAX(activityID) AS maxID FROM activities");
            int ID = 1; // Default value if no activity exists
            if (resultset.next()) 
            {
                ID = resultset.getInt("maxID") + 1;
            }        
            String add = "INSERT INTO activities(activity_name, activity_tag, activity_quota, activity_date, activity_time, activity_place, activity_description, activityID,current_quota,likeCount,dislikeCount) VALUES ('" + name + "' , '" + tagType + "' , '" +Quota+ "' , '" + date2 + "' , '" + time_of_activity + "','" + activity_place + "','" + activity_definition+ "','" + ID +"','"+ 1 + "','" + 0 + "','" + 0 + "' ) ";
            String add2 = "INSERT INTO enrolledActivities(userID, actID) VALUES ('"+ MainManager.user.getID() + "' , '" + ID  +"') ";
            stm.execute(add);
            stm.execute(add2);
            stm.close();
            Activity newActivity = new Activity(ID);
            MainManager.allActivities.add(newActivity);
            MainManager.user.enrolledActivities.add(newActivity);
        } catch (SQLException ex) {
            // TODO: handle exception
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_CreatingActivityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void createActivity() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CreateActivity a = new CreateActivity();
                a.setExtendedState(JFrame.MAXIMIZED_BOTH);
                a.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CHAT;
    private javax.swing.JRadioButton CHESS;
    private javax.swing.JRadioButton CINEMA;
    private javax.swing.JButton CreateActivity_Button;
    private javax.swing.JButton CreatingActivity;
    private javax.swing.JRadioButton DANCE;
    private javax.swing.JTextField GetDay;
    private javax.swing.JTextArea GetDescription;
    private javax.swing.JTextField GetHour;
    private javax.swing.JTextField GetMinute;
    private javax.swing.JTextField GetMonth;
    private javax.swing.JTextField GetName;
    private javax.swing.JTextField GetPlace;
    private javax.swing.JTextField GetQuota;
    private javax.swing.JTextField GetYear;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel NewActivityLabel;
    private javax.swing.JLabel QuotaLabel;
    private javax.swing.JRadioButton SPORTS;
    private javax.swing.JLabel TagsLabel;
    private javax.swing.JRadioButton VIDEOGAME;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel newActivity_Date;
    private javax.swing.JLabel newActivity_Day;
    private javax.swing.JLabel newActivity_Month;
    private javax.swing.JLabel newActivity_Place;
    private javax.swing.JLabel newActivity_Place1;
    private javax.swing.JLabel newActivity_Time;
    private javax.swing.JLabel newActivity_Year;
    // End of variables declaration//GEN-END:variables
}
