
public class CreateActivity extends javax.swing.JFrame {

    /**
     * Creates new form CreateActivity
     */
    public CreateActivity() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        newActivity_name = new javax.swing.JLabel();
        newActivity_tags = new javax.swing.JLabel();
        CHESS = new javax.swing.JRadioButton();
        SPORTS = new javax.swing.JRadioButton();
        CHAT = new javax.swing.JRadioButton();
        VIDEOGAME = new javax.swing.JRadioButton();
        CINEMA = new javax.swing.JRadioButton();
        newActivity_quota = new javax.swing.JLabel();
        GetName = new javax.swing.JTextField();
        newActivity_Date = new javax.swing.JLabel();
        newActivity_Day = new javax.swing.JLabel();
        newActivity_Month = new javax.swing.JLabel();
        newActivity_Year = new javax.swing.JLabel();
        GetQuota = new javax.swing.JTextField();
        GetMonth = new javax.swing.JTextField();
        GetYear = new javax.swing.JTextField();
        newActivity_Time = new javax.swing.JLabel();
        GetPlace = new javax.swing.JTextField();
        newActivity_Place = new javax.swing.JLabel();
        GetDay = new javax.swing.JTextField();
        GetTime = new javax.swing.JTextField();
        newActivity_Place1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        GetDescription = new javax.swing.JTextArea();
        CreateActivity_Button = new javax.swing.JButton();
        DANCE = new javax.swing.JRadioButton();
        CreatingActivity = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 900));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel1.setText("New Activity");

        newActivity_name.setBackground(new java.awt.Color(255, 255, 255));
        newActivity_name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newActivity_name.setText("Name");

        newActivity_tags.setBackground(new java.awt.Color(255, 255, 255));
        newActivity_tags.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newActivity_tags.setText("Tags");

        CHESS.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        CHESS.setText("CHESS");
        CHESS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHESSActionPerformed(evt);
            }
        });

        SPORTS.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        SPORTS.setText("SPORTS");
        SPORTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPORTSActionPerformed(evt);
            }
        });

        CHAT.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        CHAT.setText("CHAT");
        CHAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHATActionPerformed(evt);
            }
        });

        VIDEOGAME.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        VIDEOGAME.setText("VIDEOGAME");
        VIDEOGAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VIDEOGAMEActionPerformed(evt);
            }
        });

        CINEMA.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        CINEMA.setText("CINEMA");

        newActivity_quota.setBackground(new java.awt.Color(255, 255, 255));
        newActivity_quota.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newActivity_quota.setText("Quota");

        GetName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetNameActionPerformed(evt);
            }
        });

        newActivity_Date.setBackground(new java.awt.Color(255, 255, 255));
        newActivity_Date.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newActivity_Date.setText("Date");

        newActivity_Day.setBackground(new java.awt.Color(255, 255, 255));
        newActivity_Day.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newActivity_Day.setText("Day");

        newActivity_Month.setBackground(new java.awt.Color(255, 255, 255));
        newActivity_Month.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newActivity_Month.setText("Month");

        newActivity_Year.setBackground(new java.awt.Color(255, 255, 255));
        newActivity_Year.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newActivity_Year.setText("Year");

        GetQuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetQuotaActionPerformed(evt);
            }
        });

        GetMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetMonthActionPerformed(evt);
            }
        });

        GetYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetYearActionPerformed(evt);
            }
        });

        newActivity_Time.setBackground(new java.awt.Color(255, 255, 255));
        newActivity_Time.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newActivity_Time.setText("Time");

        GetPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetPlaceActionPerformed(evt);
            }
        });

        newActivity_Place.setBackground(new java.awt.Color(255, 255, 255));
        newActivity_Place.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newActivity_Place.setText("Place");

        GetDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetDayActionPerformed(evt);
            }
        });

        GetTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetTimeActionPerformed(evt);
            }
        });

        newActivity_Place1.setBackground(new java.awt.Color(255, 255, 255));
        newActivity_Place1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newActivity_Place1.setText("Description");

        GetDescription.setColumns(20);
        GetDescription.setRows(5);
        jScrollPane1.setViewportView(GetDescription);

        CreateActivity_Button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CreateActivity_Button.setText("Create Activity");
        CreateActivity_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActivity_ButtonActionPerformed(evt);
            }
        });

        DANCE.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        DANCE.setText("DANCE");

        CreatingActivity.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CreatingActivity.setText("Create Activity");
        CreatingActivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatingActivityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newActivity_name, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newActivity_tags, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newActivity_quota, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newActivity_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newActivity_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newActivity_Place, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(newActivity_Place1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GetTime, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CHESS, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SPORTS, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(CHAT, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(VIDEOGAME, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(CINEMA, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DANCE, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(GetQuota, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GetName, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GetPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(newActivity_Day, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GetDay, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(newActivity_Month, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GetMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(newActivity_Year, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GetYear, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CreateActivity_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(255, 255, 255)
                        .addComponent(CreatingActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newActivity_name, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GetName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SPORTS, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CHAT, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CHESS, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newActivity_tags, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VIDEOGAME, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CINEMA, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DANCE, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newActivity_quota, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GetQuota, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newActivity_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newActivity_Day, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newActivity_Month, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newActivity_Year, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GetMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GetYear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GetDay, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newActivity_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GetTime, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newActivity_Place, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GetPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(newActivity_Place1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(CreateActivity_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CreatingActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CHATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHATActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CHATActionPerformed

    private void CHESSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHESSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CHESSActionPerformed

    private void SPORTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPORTSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SPORTSActionPerformed

    private void GetNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GetNameActionPerformed

    private void GetQuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetQuotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GetQuotaActionPerformed

    private void GetMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GetMonthActionPerformed

    private void GetYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GetYearActionPerformed

    private void GetPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetPlaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GetPlaceActionPerformed

    private void GetDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GetDayActionPerformed

    private void GetTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GetTimeActionPerformed

    private void CreateActivity_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActivity_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateActivity_ButtonActionPerformed

    private void VIDEOGAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VIDEOGAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VIDEOGAMEActionPerformed

    private void CreatingActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatingActivityActionPerformed
        // TODO add your handling code here:
        String name = GetName.getText();
        
    }//GEN-LAST:event_CreatingActivityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateActivity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CHAT;
    private javax.swing.JRadioButton CHESS;
    private javax.swing.JRadioButton CINEMA;
    private javax.swing.JButton CreateActivity_Button;
    private javax.swing.JButton CreatingActivity;
    private javax.swing.JRadioButton DANCE;
    private javax.swing.JTextField GetDay;
    private javax.swing.JTextArea GetDescription;
    private javax.swing.JTextField GetMonth;
    private javax.swing.JTextField GetName;
    private javax.swing.JTextField GetPlace;
    private javax.swing.JTextField GetQuota;
    private javax.swing.JTextField GetTime;
    private javax.swing.JTextField GetYear;
    private javax.swing.JRadioButton SPORTS;
    private javax.swing.JRadioButton VIDEOGAME;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel newActivity_Date;
    private javax.swing.JLabel newActivity_Day;
    private javax.swing.JLabel newActivity_Month;
    private javax.swing.JLabel newActivity_Place;
    private javax.swing.JLabel newActivity_Place1;
    private javax.swing.JLabel newActivity_Time;
    private javax.swing.JLabel newActivity_Year;
    private javax.swing.JLabel newActivity_name;
    private javax.swing.JLabel newActivity_quota;
    private javax.swing.JLabel newActivity_tags;
    // End of variables declaration//GEN-END:variables
}
