import javax.swing.JPanel;

public class FriendMsgPage extends javax.swing.JFrame {

    private Account account;
    private FriendChat friendChat;
    private final boolean type = false;

    public FriendMsgPage(Account account) {
        initComponents();
        addToInitComponents();

        receiverNameL.setText(account.getUserName());  

        friendChat = new FriendChat(account.getID(), account.getUserName());
        this.account = account;

        Refresh.adjustTimerForFriendChat(false, friendChat, account, chatPanel);
    }
    
    private void addToInitComponents(){
        //Scroll Bar UI
        chatPane.getVerticalScrollBar().setUI(new NewScrollBarUI());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton2 = new javax.swing.JButton();
        receiverNameL = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        chatPane = new javax.swing.JScrollPane();
        chatPanel = new javax.swing.JPanel();
        chatInput = new javax.swing.JTextField();
        sendMessageB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jButton2.setText("jButton2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.ipady = 57;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 25, 0, 0);
        getContentPane().add(jButton2, gridBagConstraints);

        receiverNameL.setText("receiverNameL");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = 32;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 62, 0, 29);
        getContentPane().add(receiverNameL, gridBagConstraints);

        jSeparator1.setForeground(new java.awt.Color(102, 102, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 408;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 0, 29);
        getContentPane().add(jSeparator1, gridBagConstraints);

        chatPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        chatPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        chatPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        chatPanel.setOpaque(false);

        javax.swing.GroupLayout chatPanelLayout = new javax.swing.GroupLayout(chatPanel);
        chatPanel.setLayout(chatPanelLayout);
        chatPanelLayout.setHorizontalGroup(
            chatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        chatPanelLayout.setVerticalGroup(
            chatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        chatPane.setViewportView(chatPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 389;
        gridBagConstraints.ipady = 390;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 0, 29);
        getContentPane().add(chatPane, gridBagConstraints);

        chatInput.setText("jTextField1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 259;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 25, 0, 0);
        getContentPane().add(chatInput, gridBagConstraints);

        sendMessageB.setText("jButton4");
        sendMessageB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        sendMessageB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMessageBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.ipady = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 6, 0);
        getContentPane().add(sendMessageB, gridBagConstraints);

        pack();
    }// </editor-fold>                        

    private void sendMessageBActionPerformed(java.awt.event.ActionEvent evt) {                                             
        if(chatInput.getText().length() > 0){
            //Create and send the message;
            Message msg = new Message(0, chatInput.getText(),
                                      MainManager.user, account.getID(),
                                      null, type, friendChat);

            //Refresh messages;
            friendChat.getChat(account, chatPanel);
            //Adjust scrollbar's position to bottom after sending message;
            // TODO add your handling code here:
            chatPane.getVerticalScrollBar().setValue(chatPane.getVerticalScrollBar().getMaximum());
            // TODO add your handling code here:
            // Get Messages
            // Date should not be null;
        }
    }                                            

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    private javax.swing.JPanel chatPanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel receiverNameL;
    private javax.swing.JScrollPane chatPane;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton sendMessageB;
    private javax.swing.JTextField chatInput;
    // End of variables declaration                   
}
