/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mainmanager;

import javax.swing.Popup;
import javax.swing.PopupFactory;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionListener;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JScrollBar;

/**
 *
 * @author ereno
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public boolean isNotiDisplayed;
    private Pop noti;
    
    public MainPage() {

        isNotiDisplayed = false;
        
        initComponents();//Created by the netbeans itself
        addToInitComponents();//Additions to the creation
        
        this.setVisible(true);
        this.setBackground(Color.WHITE);
        
    }
        
    private void addToInitComponents(){
        //Panels
        this.activityPanel.setBackground(Color.black);
        this.chat_Profile_SettingsPanel.setBackground(Color.pink);
        
        //Frame
        this.pack();
        
        //Labels
        searchActivityBar.setText("Seach Activity By Typing");
        
        //Buttons
        //-------   
        //CreateActivityButton
        createActivityButton.setText(null);
        ImageIcon icon = new ImageIcon("plus.png");
        Image img = icon.getImage() ; 
        //createActivityButton.getWidth()
        //createActivityButton.getHeight()
        Image newimg = img.getScaledInstance( 10, 10, java.awt.Image.SCALE_SMOOTH) ; 
        icon = new ImageIcon( newimg );
        createActivityButton.setIcon(icon);
        
        //NotificationsButton
        notificationsButton.setBounds(notificationsButton.getX(), notificationsButton.getY(), 300, 25);
        notificationsButton.setBorder(new CircledBorder(10));//10 is the radius
        notificationsButton.setForeground(Color.BLUE);
        
        noti = new Pop(this);
        //-------
                    
        /*
        addBtn.setBounds(x_pos, y_pos, 30, 25);
        addBtn.setBorder(new RoundedBorder(10)); //10 is the radius
        addBtn.setForeground(Color.BLUE);
        */
      
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        mainPagePanel = new javax.swing.JPanel();
        calendar_EnrolledActivitiesPanel = new javax.swing.JPanel();
        calendarPanel = new javax.swing.JPanel();
        CalendarLabel = new javax.swing.JLabel();
        enrolledActivitiesPanel = new javax.swing.JPanel();
        enrolledActivitiesLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        activitiesText = new javax.swing.JTextPane();
        activityPanel = new javax.swing.JPanel();
        searchActivityBar = new javax.swing.JTextField();
        activities = new javax.swing.JPanel();
        createActivityButton = new javax.swing.JButton();
        chat_Profile_SettingsPanel = new javax.swing.JPanel();
        notificationsButton = new javax.swing.JButton();
        profileButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        profileName = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(1000, 600));

        mainPagePanel.setBackground(new java.awt.Color(255, 255, 255));

        calendar_EnrolledActivitiesPanel.setBackground(new java.awt.Color(255, 255, 255));
        calendar_EnrolledActivitiesPanel.setPreferredSize(new java.awt.Dimension(196, 600));
        calendar_EnrolledActivitiesPanel.setLayout(new java.awt.BorderLayout());

        calendarPanel.setBackground(new java.awt.Color(255, 255, 255));
        calendarPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        calendarPanel.setForeground(new java.awt.Color(0, 204, 204));
        calendarPanel.setAutoscrolls(true);
        calendarPanel.setPreferredSize(new java.awt.Dimension(180, 250));

        CalendarLabel.setBackground(new java.awt.Color(0, 204, 204));
        CalendarLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CalendarLabel.setForeground(new java.awt.Color(0, 51, 102));
        CalendarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CalendarLabel.setText("Calendar");
        CalendarLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        CalendarLabel.setPreferredSize(new java.awt.Dimension(56, 20));

        javax.swing.GroupLayout calendarPanelLayout = new javax.swing.GroupLayout(calendarPanel);
        calendarPanel.setLayout(calendarPanelLayout);
        calendarPanelLayout.setHorizontalGroup(
            calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CalendarLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
        );
        calendarPanelLayout.setVerticalGroup(
            calendarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calendarPanelLayout.createSequentialGroup()
                .addComponent(CalendarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 215, Short.MAX_VALUE))
        );

        calendar_EnrolledActivitiesPanel.add(calendarPanel, java.awt.BorderLayout.NORTH);

        enrolledActivitiesPanel.setBackground(new java.awt.Color(0, 204, 204));
        enrolledActivitiesPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)));
        enrolledActivitiesPanel.setPreferredSize(new java.awt.Dimension(180, 250));

        enrolledActivitiesLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        enrolledActivitiesLabel.setForeground(new java.awt.Color(0, 51, 102));
        enrolledActivitiesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enrolledActivitiesLabel.setText("Enrolled Activities");
        enrolledActivitiesLabel.setPreferredSize(new java.awt.Dimension(175, 20));

        activitiesText.setPreferredSize(new java.awt.Dimension(151, 150));
        jScrollPane2.setViewportView(activitiesText);

        javax.swing.GroupLayout enrolledActivitiesPanelLayout = new javax.swing.GroupLayout(enrolledActivitiesPanel);
        enrolledActivitiesPanel.setLayout(enrolledActivitiesPanelLayout);
        enrolledActivitiesPanelLayout.setHorizontalGroup(
            enrolledActivitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(enrolledActivitiesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
        enrolledActivitiesPanelLayout.setVerticalGroup(
            enrolledActivitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enrolledActivitiesPanelLayout.createSequentialGroup()
                .addComponent(enrolledActivitiesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        calendar_EnrolledActivitiesPanel.add(enrolledActivitiesPanel, java.awt.BorderLayout.SOUTH);

        mainPagePanel.add(calendar_EnrolledActivitiesPanel);

        activityPanel.setBackground(new java.awt.Color(255, 255, 255));
        activityPanel.setForeground(new java.awt.Color(255, 255, 255));

        searchActivityBar.setForeground(new java.awt.Color(0, 204, 204));
        searchActivityBar.setText("jTextField1");
        searchActivityBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        searchActivityBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActivityBarActionPerformed(evt);
            }
        });

        activities.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        activities.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout activitiesLayout = new javax.swing.GroupLayout(activities);
        activities.setLayout(activitiesLayout);
        activitiesLayout.setHorizontalGroup(
            activitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );
        activitiesLayout.setVerticalGroup(
            activitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        createActivityButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\ereno\\Documents\\NetBeansProjects\\MainManager\\src\\images\\plus.png")); // NOI18N
        createActivityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActivityButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout activityPanelLayout = new javax.swing.GroupLayout(activityPanel);
        activityPanel.setLayout(activityPanelLayout);
        activityPanelLayout.setHorizontalGroup(
            activityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activityPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(activityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(activities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(activityPanelLayout.createSequentialGroup()
                        .addComponent(searchActivityBar, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(createActivityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        activityPanelLayout.setVerticalGroup(
            activityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activityPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(activityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchActivityBar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createActivityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(activities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        mainPagePanel.add(activityPanel);

        chat_Profile_SettingsPanel.setBackground(new java.awt.Color(255, 255, 255));
        chat_Profile_SettingsPanel.setForeground(new java.awt.Color(255, 255, 255));

        notificationsButton.setBackground(new java.awt.Color(255, 255, 153));
        notificationsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationsButtonActionPerformed(evt);
            }
        });

        profileButton.setBackground(new java.awt.Color(255, 102, 102));
        profileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        profileName.setText("ProfileName\n");

        javax.swing.GroupLayout chat_Profile_SettingsPanelLayout = new javax.swing.GroupLayout(chat_Profile_SettingsPanel);
        chat_Profile_SettingsPanel.setLayout(chat_Profile_SettingsPanelLayout);
        chat_Profile_SettingsPanelLayout.setHorizontalGroup(
            chat_Profile_SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chat_Profile_SettingsPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(chat_Profile_SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(chat_Profile_SettingsPanelLayout.createSequentialGroup()
                        .addComponent(profileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(notificationsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(chat_Profile_SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
            .addGroup(chat_Profile_SettingsPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(profileName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        chat_Profile_SettingsPanelLayout.setVerticalGroup(
            chat_Profile_SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chat_Profile_SettingsPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(chat_Profile_SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(notificationsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(profileName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPagePanel.add(chat_Profile_SettingsPanel);

        getContentPane().add(mainPagePanel, java.awt.BorderLayout.CENTER);

        menuPanel.setBackground(new java.awt.Color(0, 204, 204));
        menuPanel.setPreferredSize(new java.awt.Dimension(100, 600));

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        getContentPane().add(menuPanel, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>                        

    private void createActivityButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        this.dispose();
        JFrame createActivityFrame = new CreateActivity();
        
    }                                                    

    private void notificationsButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
        noti.decideAction();//To decide whether to show the popup or hide it;

    }                                                   

    private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        this.dispose();
        JFrame profileFrame = new ProfilePage();
    }                                             

    private void searchActivityBarActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    /**
     * @param args the command line arguments
     */
    
    public int positionX_profileP(){
        return chat_Profile_SettingsPanel.getX();
    }
    
    public int positionY_profileP(){
        return chat_Profile_SettingsPanel.getY();
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel CalendarLabel;
    private javax.swing.JPanel activities;
    private javax.swing.JTextPane activitiesText;
    private javax.swing.JPanel activityPanel;
    private javax.swing.JPanel calendarPanel;
    private javax.swing.JPanel calendar_EnrolledActivitiesPanel;
    private javax.swing.JPanel chat_Profile_SettingsPanel;
    private javax.swing.JButton createActivityButton;
    private javax.swing.JLabel enrolledActivitiesLabel;
    private javax.swing.JPanel enrolledActivitiesPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainPagePanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton notificationsButton;
    private javax.swing.JButton profileButton;
    private javax.swing.JLabel profileName;
    private javax.swing.JTextField searchActivityBar;
    // End of variables declaration                   
}
